In [24]:
import pandas as pd
import json
import csv
import numpy as np
from datetime import datetime, timedelta

In [14]:
f = open("interventionscitoyendo.csv", 'r')

In [74]:
df_crimes = pd.read_csv("interventionscitoyendo.csv",delimiter=',', encoding = "ISO-8859-1").dropna()

In [75]:
df_crimes.shape

(143271, 8)

In [18]:
df_crimes.head()

,CATEGORIE,DATE,QUART,PDQ,X,Y,LONGITUDE,LATITUDE
0,Vol de véhicule à moteur,2018-09-13,jour,30.0,294904.159001,5.047549e+06,-73.626778,45.567780
1,Vol de véhicule à moteur,2018-04-30,jour,30.0,294904.159001,5.047549e+06,-73.626778,45.567780
2,Vol de véhicule à moteur,2018-09-01,nuit,7.0,290274.565000,5.042150e+06,-73.685928,45.519122
3,Méfait,2017-07-21,jour,21.0,0.000000,0.000000e+00,1.000000,1.000000
4,Méfait,2017-07-29,jour,12.0,0.000000,0.000000e+00,1.000000,1.000000

In [99]:
df_crimes = df_crimes.sort_values(by=["DATE"])

In [100]:
df_crimes.head()

,CATEGORIE,DATE,QUART,PDQ,X,Y,LONGITUDE,LATITUDE
91456,Introduction,2015-01-01,soir,8.0,289171.124993,5.032933e+06,-73.699759,45.436155
13686,Introduction,2015-01-01,soir,44.0,298915.433995,5.046912e+06,-73.575381,45.562090
8370,Introduction,2015-01-01,soir,13.0,297145.531007,5.032846e+06,-73.597834,45.435501
16961,Vol dans / sur véhicule à moteur,2015-01-01,jour,20.0,297404.343998,5.040277e+06,-73.594638,45.502376
237,Vol de véhicule à moteur,2015-01-01,nuit,5.0,288453.923000,5.037011e+06,-73.709062,45.472834

In [48]:
base = datetime(2015,1,1)
x = 1
numdays=1648
date_list = [base + timedelta(days=x) for x in range(0, numdays)]

In [49]:
date_list[-1]

datetime.datetime(2019, 7, 6, 0, 0)

In [105]:
df_pdq = df_crimes.loc[df_crimes["PDQ"]==33.0]
print(df_pdq.shape)
df_pdq.head(50)

(2027, 8)

,CATEGORIE,DATE,QUART,PDQ,X,Y,LONGITUDE,LATITUDE
98779,Introduction,2015-01-03,jour,33.0,294968.614000,5.042711e+06,-73.625855,45.524246
10164,Méfait,2015-01-03,jour,33.0,295050.966010,5.043082e+06,-73.624808,45.527589
89961,Vols qualifiés,2015-01-10,jour,33.0,295284.474000,5.043436e+06,-73.621826,45.530780
10353,Vol dans / sur véhicule à moteur,2015-01-10,jour,33.0,294746.899002,5.043434e+06,-73.628708,45.530749
7166,Introduction,2015-01-10,soir,33.0,294988.016010,5.043179e+06,-73.625616,45.528455
84813,Vols qualifiés,2015-01-11,soir,33.0,295217.514000,5.043313e+06,-73.622681,45.529664
48659,Vol dans / sur véhicule à moteur,2015-01-13,soir,33.0,0.000000,0.000000e+00,1.000000,1.000000
59556,Méfait,2015-01-13,soir,33.0,0.000000,0.000000e+00,1.000000,1.000000
64718,Vol dans / sur véhicule à moteur,2015-01-13,nuit,33.0,0.000000,0.000000e+00,1.000000,1.000000
101923,Introduction,2015-01-14,jour,33.0,295242.821003,5.042723e+06,-73.622345,45.524355
3236,Vol de véhicule à moteur,2015-01-14,nuit,33.0,294616.672999,5.043121e+06,-73.630369,45.527934
6249,Vol dans / sur véhicule à moteur,2015-01-14,jour,33.0,295421.241000,5.042996e+06,-73.620066,45.526817
105630,Vol dans / sur véhicule à moteur,2015-01-14,jour,33.0,294589.972003,5.043060e+06,-73.630710,45.527378
23410,Introduction,2015-01-15,soir,33.0,295460.915997,5.043059e+06,-73.619560,45.527386
23409,Vol dans / sur véhicule à moteur,2015-01-15,jour,33.0,295460.915997,5.043059e+06,-73.619560,45.527386
99532,Méfait,2015-01-17,jour,33.0,0.000000,0.000000e+00,1.000000,1.000000
5097,Vol dans / sur véhicule à moteur,2015-01-17,jour,33.0,295421.241000,5.042996e+06,-73.620066,45.526817
12066,Vol dans / sur véhicule à moteur,2015-01-23,jour,33.0,293597.419009,5.043403e+06,-73.643424,45.530457
73910,Introduction,2015-01-24,soir,33.0,294968.614000,5.042711e+06,-73.625855,45.524246
106675,Introduction,2015-01-24,jour,33.0,294887.062997,5.042936e+06,-73.626904,45.526273
3697,Vol de véhicule à moteur,2015-01-25,jour,33.0,294076.813001,5.043204e+06,-73.637282,45.528668
85397,Introduction,2015-01-27,jour,33.0,293962.195009,5.043606e+06,-73.638758,45.532289
1851,Vol dans / sur véhicule à moteur,2015-01-29,soir,33.0,294938.218003,5.043058e+06,-73.626251,45.527370
44679,Vol dans / sur véhicule à moteur,2015-01-29,jour,33.0,0.000000,0.000000e+00,1.000000,1.000000
99138,Méfait,2015-01-30,soir,33.0,294818.110000,5.042773e+06,-73.627783,45.524800
18214,Introduction,2015-01-31,soir,33.0,294666.917005,5.043241e+06,-73.629728,45.529008
16845,Introduction,2015-02-01,jour,33.0,293913.914000,5.043486e+06,-73.639374,45.531206
105817,Méfait,2015-02-01,jour,33.0,293621.620008,5.043461e+06,-73.643116,45.530975
19927,Introduction,2015-02-02,soir,33.0,294863.321000,5.042879e+06,-73.627206,45.525754
42194,Vol dans / sur véhicule à moteur,2015-02-04,jour,33.0,0.000000,0.000000e+00,1.000000,1.000000
56124,Méfait,2015-02-04,jour,33.0,293313.885000,5.043655e+06,-73.647060,45.532713
20320,Vol de véhicule à moteur,2015-02-04,soir,33.0,293371.205003,5.043499e+06,-73.646322,45.531313
8569,Méfait,2015-02-04,jour,33.0,295044.415002,5.043311e+06,-73.624897,45.529648
101354,Introduction,2015-02-07,jour,33.0,293696.111991,5.043641e+06,-73.642166,45.532593
89962,Introduction,2015-02-07,jour,33.0,295191.415000,5.043249e+06,-73.623014,45.529092
89956,Introduction,2015-02-07,jour,33.0,295191.415000,5.043249e+06,-73.623014,45.529092
16831,Vol dans / sur véhicule à moteur,2015-02-07,jour,33.0,294398.572993,5.043282e+06,-73.633165,45.529378
84034,Méfait,2015-02-07,jour,33.0,0.000000,0.000000e+00,1.000000,1.000000
105639,Vol dans / sur véhicule à moteur,2015-02-08,jour,33.0,293861.046994,5.043361e+06,-73.640048,45.530078
18218,Introduction,2015-02-09,jour,33.0,294666.917005,5.043241e+06,-73.629728,45.529008
6230,Méfait,2015-02-09,jour,33.0,295421.241000,5.042996e+06,-73.620066,45.526817
6232,Méfait,2015-02-09,nuit,33.0,295421.241000,5.042996e+06,-73.620066,45.526817
42601,Méfait,2015-02-09,jour,33.0,0.000000,0.000000e+00,1.000000,1.000000
42309,Vol dans / sur véhicule à moteur,2015-02-10,jour,33.0,294841.486990,5.042828e+06,-73.627485,45.525302
103052,Vol dans / sur véhicule à moteur,2015-02-10,jour,33.0,295460.915997,5.043059e+06,-73.619560,45.527386
7330,Vol dans / sur véhicule à moteur,2015-02-11,soir,33.0,294988.016010,5.043179e+06,-73.625616,45.528455
54130,Méfait,2015-02-12,jour,33.0,0.000000,0.000000e+00,1.000000,1.000000
10161,Introduction,2015-02-13,jour,33.0,295050.966010,5.043082e+06,-73.624808,45.527589
8283,Introduction,2015-02-13,soir,33.0,293696.111991,5.043641e+06,-73.642166,45.532593
107637,Introduction,2015-02-13,jour,33.0,294347.117997,5.043159e+06,-73.633821,45.528270

In [72]:
types_of_crimes = list(set(df_crimes["CATEGORIE"].values))
phase_of_day = list(set(df_crimes["QUART"].values))
print(types_of_crimes)

['Vols qualifiés', 'Infractions entrainant la mort', 'Introduction', 'Vol dans / sur véhicule à moteur', 'Vol de véhicule à moteur', 'Méfait']

In [70]:
new_data_dict = {}
for datetime_obj in date_list[:10]:
    selected_rows = df_pdq.loc[df_pdq["DATE"]==datetime_obj.strftime("%Y-%m-%d")]
    initial_crime_vector = [0.0]*6
    initial_phase_of_day_vector = [0.0]*3
    for index, row in selected_rows.iterrows():
        initial_crime_vector[types_of_crimes.index(row["CATEGORIE"])] += 1.0
        initial_phase_of_day_vector[phase_of_day.index(row["QUART"])] += 1.0
    new_data_dict[datetime_obj.strftime("%Y-%m-%d")] = initial_crime_vector + initial_phase_of_day_vector

In [71]:
new_data_dict

{'2015-01-01': [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 '2015-01-02': [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 '2015-01-03': [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0],
 '2015-01-04': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 '2015-01-05': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 '2015-01-06': [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0],
 '2015-01-07': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 '2015-01-08': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 '2015-01-09': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 '2015-01-10': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}

In [ ]:
# actual loop

In [103]:
pdq_numbers = list(set(df_crimes["PDQ"]))
print(pdq_numbers)

# for each police station
for pdq_number in pdq_numbers:
    df_pdq = df_crimes.loc[df_crimes["PDQ"]==pdq_number]
    
    indv_pdq_data_dict = {}
    
    crime_category_dict = {}
    for category in types_of_crimes+phase_of_day:
        crime_category_dict[category] = []
    
    # for each day
    for datetime_obj in date_list:
        
        selected_rows = df_pdq.loc[df_pdq["DATE"]==datetime_obj.strftime("%Y-%m-%d")]
        initial_crime_vector = [0.0]*6
        initial_phase_of_day_vector = [0.0]*3
        for index, row in selected_rows.iterrows():
            initial_crime_vector[types_of_crimes.index(row["CATEGORIE"])] += 1.0
            initial_phase_of_day_vector[phase_of_day.index(row["QUART"])] += 1.0
        indv_pdq_data_dict[datetime_obj.strftime("%Y-%m-%d")] = initial_crime_vector + initial_phase_of_day_vector
#         list_of_pdq_dicts.append(indv_pdq_data_dict)

        for category, item in zip(list(crime_category_dict.keys()), initial_crime_vector+initial_phase_of_day_vector):
            crime_category_dict[category].append(item)
        
    df_ind_pdq = pd.DataFrame(data=crime_category_dict, index=date_list)
    df_ind_pdq.to_csv("pdq_"+str(int(pdq_number))+".csv", encoding='utf-8')
    print(pdq_number)

[1.0, 3.0, 4.0, 5.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 15.0, 16.0, 20.0, 21.0, 22.0, 23.0, 24.0, 26.0, 27.0, 30.0, 31.0, 33.0, 35.0, 38.0, 39.0, 42.0, 44.0, 45.0, 46.0, 48.0, 49.0, 50.0, 55.0]
1.0
3.0
4.0
5.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
15.0
16.0
20.0
21.0
22.0
23.0
24.0
26.0
27.0
30.0
31.0
33.0
35.0
38.0
39.0
42.0
44.0
45.0
46.0
48.0
49.0
50.0
55.0